### ISSUE TITLE
Awesome technical stacks with this project!

### ISSUE THREAD

**Issue by TaylorDurden** [Hongbo-Miao/hongbomiao.com#2736]
Do you have a plan to give us a course or documentation to demonstrate all the good technical stacks with this project?

**Comment by Hongbo-Miao** [comment]
Hey @TaylorDurden thanks for the word!

This repo is currently being used by me to test and learn cutting-edge technologies which keeps changing very fast as you can see from the commit history.
When I found better alternatives, I usually removed the old ones.

If you want to learn from this repo, I would suggest first checking technologies listed in the [Tech Stack](https://github.com/Hongbo-Miao/hongbomiao.com#tech-stack) section, and go their repos to learn how to use them separately.

More importantly, focus on the concept and what problem the technology is trying to solve, instead of the technology itself.
For example, `Opossum` is the technology I am using for circuit breaker in a Node.js server. But in Go, Python, or Java projects, they have their own libraries for circuit breaker. And also for service mesh such as Istio, it has global circuit breaker for all its microservices.
So instead of focusing on `Opossum`, focus on learning what is circuit breaker, and why we introduce it. After that, if you are building a Go project, find a circuit breaker library, and try to integrate with your own Go project and experimenting.

Hope that helps! 😃
